### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by bberzinskas-tw** [wistia/terraform-provider-wistia#1]
can't resolve dns to http://registry.wistia.io/.    interested in using the project / api key resources.

**Comment by acj** [comment]
Hey, I'm sorry for the long delay. My notification settings were wrong -- now fixed.

The DNS issue was happening because TF couldn't find a copy of the provider binary, which wasn't covered in the getting started docs (d'oh). I've updated the readme to cover that along with installation of the needed tools. If you're still interested in the project, could you please give it another try?

Any details about your use case that you'd be willing to share would be appreciated, too, as this is an experimental project. My email is in my profile if you'd prefer not to share that info publicly.

**Comment by acj** [comment]
Closing since this should be fixed. If that's not the case, please let us know.
